//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP223_Bulatov_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketID { get; set; }
        public int SessionId { get; set; }
        public int SeatNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsBooked { get; set; }
        public bool IsSold { get; set; }
    
        public virtual Sessions Sessions { get; set; }
        public virtual Users Users { get; set; }
    }
}
